### ISSUE TITLE
Parent issue

### ISSUE THREAD

**Issue by chancharles92** [EspressoSystems/hotshot-primitives#1]
Reference: https://github.com/EspressoSystems/papers/issues/132

## Sprint 3

**Quorum certificate** (Binyi + Philippe)
- [x] https://github.com/EspressoSystems/hotshot-primitives/issues/2 (2.5 weeks, iterations)
- [x] https://github.com/EspressoSystems/hotshot-primitives/issues/3 (3 weeks)

**DA backup scheme** (Gus, Chengyu)
- [x] #13 (2 weeks, iterations)
- [x] https://github.com/EspressoSystems/jellyfish/issues/215 APIs and (reuse) instantiation (2 week, Chengyu)
- [x] #14 (3 weeks, Gus)
- [x] https://github.com/EspressoSystems/jellyfish/issues/118 (2 weeks, Alex)

**Stake table** (Alex: stake table; Chengyu: persistent SMT)
- [x] [Trait definition](https://github.com/EspressoSystems/hotshot-primitives/issues/8) (2 weeks, iterations)
- [x] [Persistent Sparse Merkle tree implementation](https://github.com/EspressoSystems/hotshot-primitives/issues/9) (1~2 week)
- [x] [Stake key table implementation](https://github.com/EspressoSystems/hotshot-primitives/issues/10) (1 week)

### Stretch Goal

- [x] SNARK circuit for key aggregation
- [ ] Instantiation: SNARKed aggregate signature 
- [x] https://github.com/EspressoSystems/hotshot-primitives/issues/6 (1 week)
- [x] https://github.com/EspressoSystems/hotshot-primitives/issues/7 (2 weeks)

**Comment by ggutoski** [comment]
@chancharles92 can we close this issue?
