### ISSUE TITLE
parent issue: Public-facing tech docs on VID + namespace

### ISSUE THREAD

**Issue by ggutoski** [EspressoSystems/hotshot-primitives#70]
- [ ] hackmd or white paper: random lin combo of commits
- [ ] hackmd or white paper: 2-level KZG for quadratic improvement in setup size
- [ ] blog post: Espresso's solution for VID + namespace in hotshot
